name: Clang-format

on:
  pull_request:
    paths: # only run if c++ files were changed
      - "src/*.cpp"
      - "include/*.hpp"
      - "test/src/*.cpp"

jobs:
  clang-format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited

      - name: Run clang-format
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $cpp_file_re = ".*\.[ch]pp"
          $files = "${{ steps.files.outputs.added_modified }}" -split " "
          $not_formatted = 0
          echo $files

          foreach($file in $files) {
            if ($file -match $cpp_file_re){ # if it's a c++ file
              clang-format -Werror -n $file
              $not_formatted = $LASTEXITCODE # will be 0 if formatted, 1 if not
              echo $not_formatted
            }
          }

          if ($not_formatted -ne 0) {
            # add a comment saying so
            gh pr comment ${{ github.event.number }} `
              -F ${{ github.workspace }}/.github/clang-format-msg.txt
            Write-Output "::error::A file was not formatted"
          }
