name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        # cxx: ["g++-10", "clang++-12", "cl"]
        # cc: ["gcc-10", "clang-12", "cl"]
        # os: ["ubuntu-latest", "windows-latest"]

        include:
          - cxx: g++-10
            cc: gcc-10
            os: ubuntu-latest
            triplet: x64-linux
            shell: bash
            esc: \

          - cxx: clang++-12
            cc: clang-12
            os: ubuntu-latest
            triplet: x64-linux
            shell: bash
            esc: \

          - cxx: cl
            cc: cl
            os: windows-latest
            triplet: x64-windows
            shell: cmd
            esc: ^
            init: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64'

      fail-fast: false

    env:
      CXX: ${{ matrix.cxx }}
      CC: ${{ matrix.cc }}
      build_dir: ${{ github.workspace }}/build/${{ matrix.CXX }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        shell: ${{ matrix.shell }}
        run: |
          ${{ matrix.init }}
          cmake -B "${{ env.build_dir }}" -S "${{ github.workspace }}" -G Ninja ${{ matrix.esc}}
           -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_TESTS=ON            ${{ matrix.esc }}
           -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}

      - name: Build
        run: cmake --build ${{ env.build_dir }} --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{ env.build_dir }}/test
        run: ctest -C ${{ env.BUILD_TYPE }}
