name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        config:
          - cxx: clang++-14
            cc: clang-14

          - cxx: g++-10
            cc: gcc-10

    env:
      CXX: ${{ matrix.cxx }}
      CC: ${{ matrix.cc }}
      build_dir: ${{ github.workspace }}/build/${{ matrix.CXX }}

    runs-on: ubuntu-latest

    steps:
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        run: |
          cmake -B ${{ env.build_dir }} -S ${{ github.workspace }} -G Ninja \
           -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_TESTS=ON        \
           -DVCPKG_TARGET_TRIPLET=x64-linux

      - name: Build
        run: cmake --build ${{ env.build_dir }} --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{ env.build_dir }}/test
        run: ctest -C ${{ env.BUILD_TYPE }}
