name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        # cxx: ["g++-10", "clang++-12", "cl"]
        # cc: ["gcc-10", "clang-12", "cl"]
        # os: ["ubuntu-latest", "windows-latest"]

        include:
          - cxx: g++-10
            cc: gcc-10
            os: ubuntu-latest
            triplet: x64-linux

          - cxx: clang++-12
            cc: clang-12
            os: ubuntu-latest
            triplet: x64-linux

          - cxx: ""
            cc: ""
            os: windows-latest
            triplet: x64-windows

      fail-fast: false

    env:
      CXX: ${{ matrix.cxx }}
      CC: ${{ matrix.cc }}
      build_dir: ${{ github.workspace }}/build/${{ matrix.CXX }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        shell: bash
        run: |
          if [[ ${{ matrix.os }} = "windows-latest" ]]; then
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          fi
          cmake -B "${{ env.build_dir }}" -S "${{ github.workspace }}" -G Ninja \
           -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_TESTS=ON        \
           -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}

      - name: Build
        run: cmake --build ${{ env.build_dir }} --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{ env.build_dir }}/test
        run: ctest -C ${{ env.BUILD_TYPE }}
