name: CMake Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        cxx: ["g++-10", "clang++-12"]
        cc: ["gcc-10", "clang-12"]

        # exclude different c and c++ compilers
        exclude:
          - cxx: clang++-12
            cc: gcc-10

          - cxx: g++-10
            cc: clang-12

      fail-fast: false

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.cxx }}
      CC: ${{ matrix.cc }}
      build_dir: ${{ github.workspace }}/build/${{ matrix.cxx }}

    steps:
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        run: |
          cmake -B "${{ env.build_dir }}" -S "${{ github.workspace }}" -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_TESTS=ON           \
            -DVCPKG_TARGET_TRIPLET=x64-linux

      - name: Build
        run: cmake --build ${{ env.build_dir }} --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.build_dir }}/test
        run: ctest -C ${{ env.BUILD_TYPE }}
