name: CMake Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    env:
      CXX: cl
      CC: cl
      build_dir: ${{ github.workspace }}/build

    steps:
      - name: Install Ninja
        uses: urkle/action-get-ninja@v1

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create build directory
        run: cmake -E make_directory ${{ env.build_dir }}"

      - name: Configure CMake
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -B "${{ env.build_dir }}" -S "${{ github.workspace }}" -G Ninja ^
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DBUILD_TESTS=ON           ^
            -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build ${{ env.build_dir }} --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ env.build_dir }}/test
        run: ctest -C ${{ env.BUILD_TYPE }}
